/*SELECT TOP (1000) [ID]
      ,[Reason_for_absence]
      ,[Month_of_absence]
      ,[Day_of_the_week]
      ,[Seasons]
      ,[Transportation_expense]
      ,[Distance_from_Residence_to_Work]
      ,[Service_time]
      ,[Age]
      ,[Work_load_Average_day]
      ,[Hit_target]
      ,[Disciplinary_failure]
      ,[Education]
      ,[Son]
      ,[Social_drinker]
      ,[Social_smoker]
      ,[Pet]
      ,[Weight]
      ,[Height]
      ,[Body_mass_index]
      ,[Absenteeism_time_in_hours]
  FROM [Proje2].[dbo].[Absenteeism_at_work] ---Eklediðimiz dbnin ilk 100 satýrýný görüntüledik.*/